env:
  browser: true
  es6: true
  jest: true

parser: babel-eslint
extends:
  - airbnb-base
  - 'plugin:lodash-fp/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  comma-dangle: [2, 'always-multiline']
  no-restricted-syntax: [2, 'WithStatement']
  no-param-reassign: [2, { "props": false }]
  no-await-in-loop: 0
  no-bitwise: 0

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  - jest
  - no-for-of-loops
